output "master_ip" {
  value = google_compute_instance.k8s_master.network_interface.0.access_config.0.nat_ip
}

output "worker_ip" {
  value = google_compute_instance.k8s_worker.network_interface.0.access_config.0.nat_ip
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.
    ---
    master:
      internal_ip: "10.240.0.10"
      external_ip: "${google_compute_instance.k8s_master.network_interface.0.access_config.0.nat_ip}"
    DOC
  filename = "../config/tf_ansible_vars_file.yml"
}

# Export Terraform variable values to an Ansible inventory.txt file
resource "local_file" "tf_ansible_inventory_file_new" {
  content  = <<-DOC
    [master]
    ${google_compute_instance.k8s_master.network_interface.0.access_config.0.nat_ip}
    [worker]
    ${google_compute_instance.k8s_worker.network_interface.0.access_config.0.nat_ip}
    DOC
  filename = "../config/inventory.txt"
}